### ISSUE TITLE
Autoloading of nixDir/nixConfigurations does not work

### ISSUE THREAD

**Issue by noverby** [accelbread/flakelight#2]
With the following Nixos Configuration:
```nix
# nixosConfigurations/system.nix
{inputs, ...}:
inputs.lib.nixosSystem {
  system = "x86_64-linux";
  modules = [];
}
```

I get the following error:
```bash
❯ sudo nixos-rebuild build --flake .#system
building the system configuration...
error: A definition for option `nixosConfigurations.system' is not of type `nixosConfiguration'. Definition values:
 In `/nix/store/ksaq37y8nn0w6a1hxianxr19n327abq0-source/builtinModules/nixDir.nix': <function, args: {inputs}>
```

**Comment by accelbread** [comment]
Hi, thanks for the report!

This was because the NixOS configuration attribute values have to be the actual configuration value, and above is setting it to a function that returns a configuration.

I have added the ability to configure it like this in 6d00e0f544ddd7849a9104414c5d76cc15adb8a2.

You should now be able to configure it like that as follows:

```nix
# nixosConfigurations/system.nix
{inputs, ...}:
inputs.nixpkgs.lib.nixosSystem {
  system = "x86_64-linux";
  modules = [];
}
```

**Comment by noverby** [comment]
Yes, that solves the problem! Thanks!
