### ISSUE TITLE
Support deep autoloading 

### ISSUE THREAD

**Issue by noverby** [accelbread/flakelight#4]
It seems autoloading is only supporting one directory level for autoloading. 

So this works:
```
nix/packages/pkg1.nix
```
But not this:
```
nix/packages/pkg-group/pkg1.nix
```

**Comment by accelbread** [comment]
Hmm, I'm not sure how this would generalize.

Right now we have, in order that is checked for:

- `nix/packages.nix` returns the value to set `packages` to. This is pretty clear what the user intended.
- `nix/packages/default.nix` returns the value to set `packages` to. With Nix it would be expected that `default.nix` should set what the folder evaluates to, and allows user to keep full control but put all files in a `packages` folder.
- `nix/packages/` without a `default.nix` grabs all the nix files in the directory and sets `packages` to an attrset with names from file names mapping to importing that file. This makes sense since with `nix/packages/a.nix` and `nix/packages/b.nix`, the user wants to set `packages.a` and `packages.b`.

Not sure what `nix/packages/pkg-group/pkg1.nix` would be. I would assume it would set `packages.pkg-group.pkg1` though that is not valid since `packages.x86_64-linux.pkg-group.pkg1` is not valid. Only attribute, as far as I know, that allows arbitrary structure is `legacyPackages`.

**Comment by noverby** [comment]
I didn't know directory-based package categories will be deprecated in favor of meta.categories with [RFC 146](https://github.com/NixOS/rfcs/pull/146).

Which means supporting this does not make sense anymore.
